name: Setup Nucleus
description: Setup JBR, packaging tools, Gradle, and Node.js for Nucleus builds

inputs:
  jbr-version:
    description: 'JBR version (e.g. 25.0.2b329.66)'
    required: false
    default: '25.0.2b329.66'
  jbr-variant:
    description: 'JBR variant (jbrsdk, jbrsdk_jcef, etc.)'
    required: false
    default: 'jbrsdk'
  jbr-download-url:
    description: 'Override complete JBR download URL'
    required: false
    default: ''
  packaging-tools:
    description: 'Install xvfb, rpm, fakeroot (Linux only)'
    required: false
    default: 'true'
  flatpak:
    description: 'Install Flatpak + Freedesktop SDK 24.08 (Linux only)'
    required: false
    default: 'false'
  snap:
    description: 'Install Snapd + Snapcraft (Linux only)'
    required: false
    default: 'false'
  setup-gradle:
    description: 'Setup Gradle via gradle/actions/setup-gradle@v4'
    required: false
    default: 'true'
  setup-node:
    description: 'Setup Node.js'
    required: false
    default: 'false'
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'

outputs:
  java-home:
    description: 'Path to the JBR installation'
    value: ${{ steps.set-java-home.outputs.java-home }}

runs:
  using: composite
  steps:
    # ── JBR Download & Install ──────────────────────────────────────────
    - name: Install JBR (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -euo pipefail

        INPUT_VERSION="${{ inputs.jbr-version }}"
        INPUT_VARIANT="${{ inputs.jbr-variant }}"
        INPUT_URL="${{ inputs.jbr-download-url }}"

        if [ -n "$INPUT_URL" ]; then
          URL="$INPUT_URL"
        else
          # Parse version: 25.0.2b315.62 → version=25.0.2, build=315.62
          VERSION="${INPUT_VERSION%b*}"
          BUILD="${INPUT_VERSION#*b}"

          ARCH="$(uname -m)"
          case "$ARCH" in
            x86_64)  JBR_ARCH="x64" ;;
            aarch64) JBR_ARCH="aarch64" ;;
            *)       echo "Unsupported architecture: $ARCH"; exit 1 ;;
          esac

          URL="https://cache-redirector.jetbrains.com/intellij-jbr/${INPUT_VARIANT}-${VERSION}-linux-${JBR_ARCH}-b${BUILD}.tar.gz"
        fi

        echo "Downloading JBR from: $URL"
        curl -fL -o jbr.tar.gz "$URL"
        mkdir -p "$RUNNER_TEMP/jbr"
        tar -xzf jbr.tar.gz -C "$RUNNER_TEMP/jbr"
        rm -f jbr.tar.gz

        JBR_DIR=$(find "$RUNNER_TEMP/jbr" -mindepth 1 -maxdepth 1 -type d | head -n 1)
        if [ ! -d "$JBR_DIR/bin" ]; then
          echo "Could not locate bin/ in extracted JBR"; exit 1
        fi
        echo "JAVA_HOME=$JBR_DIR" >> "$GITHUB_ENV"
        echo "$JBR_DIR/bin" >> "$GITHUB_PATH"

    - name: Install JBR (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -euo pipefail

        INPUT_VERSION="${{ inputs.jbr-version }}"
        INPUT_VARIANT="${{ inputs.jbr-variant }}"
        INPUT_URL="${{ inputs.jbr-download-url }}"

        if [ -n "$INPUT_URL" ]; then
          URL="$INPUT_URL"
        else
          VERSION="${INPUT_VERSION%b*}"
          BUILD="${INPUT_VERSION#*b}"

          ARCH="$(uname -m)"
          case "$ARCH" in
            x86_64)  JBR_ARCH="x64" ;;
            arm64)   JBR_ARCH="aarch64" ;;
            *)       echo "Unsupported architecture: $ARCH"; exit 1 ;;
          esac

          URL="https://cache-redirector.jetbrains.com/intellij-jbr/${INPUT_VARIANT}-${VERSION}-osx-${JBR_ARCH}-b${BUILD}.tar.gz"
        fi

        echo "Downloading JBR from: $URL"
        curl -fL -o jbr.tar.gz "$URL"
        mkdir -p "$RUNNER_TEMP/jbr"
        tar -xzf jbr.tar.gz -C "$RUNNER_TEMP/jbr"
        rm -f jbr.tar.gz

        ROOT_DIR=$(find "$RUNNER_TEMP/jbr" -mindepth 1 -maxdepth 1 -type d | head -n 1)
        if [ -d "$ROOT_DIR/Contents/Home/bin" ]; then
          JAVA_HOME="$ROOT_DIR/Contents/Home"
        elif [ -d "$ROOT_DIR/bin" ]; then
          JAVA_HOME="$ROOT_DIR"
        else
          echo "Could not locate bin/ in extracted JBR"; exit 1
        fi
        echo "JAVA_HOME=$JAVA_HOME" >> "$GITHUB_ENV"
        echo "$JAVA_HOME/bin" >> "$GITHUB_PATH"

    - name: Install JBR (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $ProgressPreference = 'SilentlyContinue'

        $inputVersion = '${{ inputs.jbr-version }}'
        $inputVariant = '${{ inputs.jbr-variant }}'
        $inputUrl = '${{ inputs.jbr-download-url }}'

        if ($inputUrl -ne '') {
          $url = $inputUrl
        } else {
          # Parse version: 25.0.2b315.62 → version=25.0.2, build=315.62
          $parts = $inputVersion -split 'b', 2
          $version = $parts[0]
          $build = $parts[1]

          $arch = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString().ToLower()
          switch ($arch) {
            'x64'   { $jbrArch = 'x64' }
            'arm64' { $jbrArch = 'aarch64' }
            default { Write-Error "Unsupported architecture: $arch"; exit 1 }
          }

          $url = "https://cache-redirector.jetbrains.com/intellij-jbr/${inputVariant}-${version}-windows-${jbrArch}-b${build}.zip"
        }

        Write-Host "Downloading JBR from: $url"
        Invoke-WebRequest -Uri $url -OutFile "$env:RUNNER_TEMP\jbr.zip"
        Expand-Archive -Path "$env:RUNNER_TEMP\jbr.zip" -DestinationPath "$env:RUNNER_TEMP\jbr" -Force
        Remove-Item "$env:RUNNER_TEMP\jbr.zip" -Force

        $jbrDir = Get-ChildItem "$env:RUNNER_TEMP\jbr" | Where-Object { $_.PSIsContainer } | Select-Object -First 1
        "$([string]::Format('JAVA_HOME={0}', $jbrDir.FullName))" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "$($jbrDir.FullName)in" | Out-File -FilePath $env:GITHUB_PATH -Append -Encoding utf8

    - name: Set java-home output
      id: set-java-home
      shell: bash
      run: echo "java-home=$JAVA_HOME" >> "$GITHUB_OUTPUT"

    - name: Verify JDK
      shell: bash
      run: java -version

    # ── Packaging tools (Linux only) ────────────────────────────────────
    - name: Install packaging tools (Linux)
      if: runner.os == 'Linux' && inputs.packaging-tools == 'true'
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y xvfb rpm fakeroot libdbus-1-dev
        if ! pgrep -x Xvfb >/dev/null 2>&1; then
          Xvfb :99 -screen 0 1280x1024x24 >/tmp/xvfb.log 2>&1 &
        fi
        echo "DISPLAY=:99" >> "$GITHUB_ENV"

    # ── Flatpak (Linux only) ────────────────────────────────────────────
    - name: Install Flatpak (Linux)
      if: runner.os == 'Linux' && inputs.flatpak == 'true'
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak --user install -y flathub org.freedesktop.Platform//24.08 org.freedesktop.Sdk//24.08

    # ── Snap (Linux only) ───────────────────────────────────────────────
    - name: Install Snap (Linux)
      if: runner.os == 'Linux' && inputs.snap == 'true'
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y snapd
        sudo systemctl enable --now snapd.socket || true
        sudo systemctl start snapd || true
        sudo snap wait system seed.loaded || true
        echo "/snap/bin" >> "$GITHUB_PATH"
        sudo snap install snapcraft --classic
        /snap/bin/snapcraft --version

    # ── Gradle ──────────────────────────────────────────────────────────
    - name: Setup Gradle
      if: inputs.setup-gradle == 'true'
      uses: gradle/actions/setup-gradle@v4

    # ── Node.js ─────────────────────────────────────────────────────────
    - name: Setup Node.js
      if: inputs.setup-node == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
